name: NodeJS with GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build (prod) -> output to dist/Gerador-escalas-IBAA
        run: npm run build -- --configuration production --output-path=dist/Gerador-escalas-IBAA --base-href /Gerador-escalas-IBAA/

      - name: Move files out of browser folder (if exists)
        run: |
          if [ -d "dist/Gerador-escalas-IBAA/browser" ]; then
            cp -r dist/Gerador-escalas-IBAA/browser/* dist/Gerador-escalas-IBAA/
            rm -rf dist/Gerador-escalas-IBAA/browser
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist/Gerador-escalas-IBAA/
